train:
  data_root: data/processed/data_test
  sample_rate: 48000
  segment_seconds: 5.12
  batch_size: 4
  lr: 1.0e-4
  kl_weight: 0.0
  adv_weight: 1.0
  feat_weight: 5.0
  max_steps: 1000
  log_interval: 20
  save_interval: 250
  device: cuda
  save_dir: models/vae-debug
